services:
  api-server:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  # Mount the backend code for live updates
    environment:
      - MONGO_URI=mongodb://mongo:27017/ai_assistant
      - REDIS_URL=redis://redis:6379/0
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - GOOGLE_SEARCH_API_KEY=${GOOGLE_SEARCH_API_KEY}
      - GOOGLE_SEARCH_CX=${GOOGLE_SEARCH_CX}
      - OPENAI_ASSISTANT_ID=${OPENAI_ASSISTANT_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_DRIVER=${OPENAI_DRIVER}
    depends_on:
      - mongo
      - redis

  front-app:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:5000/api/chat
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-admin:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - redis

volumes:
  mongo_data:
  redis_data:
