apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: chatbot-prod
data:
  MONGO_URI: mongodb://mongodb-0.mongodb-headless.chatbot-prod.svc.cluster.local:27017/ai_assistant
  REDIS_SENTINEL_HOST: redis.chatbot-prod.svc.cluster.local
  REDIS_DRIVER: sentinel