architecture: replication
auth:
  enabled: false

replica:
  replicaCount: 2

sentinel:
  enabled: true

persistence:
  enabled: true
  size: 8Gi

resources:
  limits:
    cpu: 0.5
    memory: 1Gi
  requests:
    cpu: 0.5
    memory: 0.5Gi