apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chatbot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {app-image-uri}
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://chatbot-app
        imagePullPolicy: Always

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chatbot-dev
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer